# Generated by Django 5.1.3 on 2024-11-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ("last_name", "first_name"),
                "verbose_name": "contact",
            },
        ),
    ]
