# Generated by Django 5.1.3 on 2024-11-13 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0002_alter_contact_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUEST", "Instance creation requested"),
                            ("SCALINGO", "Scalingo app created"),
                        ],
                        default="REQUEST",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "scalingo_application_name",
                    models.SlugField(
                        blank=True,
                        help_text="If empty, will default to sf-&lt;slug&gt;.",
                        unique=True,
                        verbose_name="Scalingo application name",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "main_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contacts.contact",
                        verbose_name="Main contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "instance",
            },
        ),
    ]
