# Generated by Django 5.1.4 on 2025-01-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instances", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instance",
            options={"ordering": ["name"], "verbose_name": "instance"},
        ),
        migrations.AddField(
            model_name="instance",
            name="scalingo_db_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Scalingo database ID"
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUEST", "Instance creation requested"),
                    ("SCALINGO_APP_CREATED", "Scalingo app created"),
                    ("SCALINGO_DB_PROVISIONED", "Scalingo database provisioned"),
                    ("SCALINGO_ENV_VARS_SET", "Environment variables set in Scalingo"),
                ],
                default="REQUEST",
                max_length=42,
                verbose_name="status",
            ),
        ),
    ]
