# Generated by Django 5.1.4 on 2025-01-13 15:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instances", "0002_alter_instance_options_instance_scalingo_db_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_from_email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        verbose_name="Default sender domain",
                    ),
                ),
                (
                    "email_host",
                    models.CharField(
                        help_text="Can only contain a domain name, without the https://",
                        max_length=100,
                        verbose_name="Email host domain",
                    ),
                ),
                (
                    "email_port",
                    models.PositiveSmallIntegerField(
                        default=25, verbose_name="Email port"
                    ),
                ),
                (
                    "email_secrets_id",
                    models.PositiveSmallIntegerField(verbose_name="Email secrets ID"),
                ),
                (
                    "email_use_tls",
                    models.BooleanField(default=False, verbose_name="Use TLS"),
                ),
                (
                    "email_use_ssl",
                    models.BooleanField(default=False, verbose_name="Use SSL"),
                ),
                (
                    "email_timeout",
                    models.PositiveSmallIntegerField(
                        default=25,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="Timeout delay",
                    ),
                ),
                (
                    "email_ssl_keyfile",
                    models.CharField(
                        blank=True,
                        help_text="Optional, can be used if either EMAIL_USE_SSL or EMAIL_USE_TLS is true.",
                        max_length=500,
                        verbose_name="Email SSL keyfile",
                    ),
                ),
                (
                    "email_ssl_certfile",
                    models.CharField(
                        blank=True,
                        help_text="Optional, can be used if either EMAIL_USE_SSL or EMAIL_USE_TLS is true.",
                        max_length=500,
                        verbose_name="Email SSL certfile",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "instance",
                "ordering": ["default_from_email"],
            },
        ),
        migrations.AddField(
            model_name="instance",
            name="allowed_hosts",
            field=models.CharField(
                blank=True,
                help_text="Can only contain a list of domain names without the https://, separated by commas",
                max_length=500,
                verbose_name="All allowed domains",
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="host_url",
            field=models.CharField(
                blank=True,
                help_text="Can only contain a domain name without the https://",
                max_length=100,
                verbose_name="Main URL domain",
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="wagtail_password_reset_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Allow users to reset their password"
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="email_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="instances.emailconfig",
                verbose_name="Email configuration",
            ),
        ),
    ]
