# Generated by Django 5.1.5 on 2025-01-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "instances",
            "0003_emailconfig_instance_allowed_hosts_instance_host_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="alwaysdata_subdomain",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Scaleway subdomain"
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="default_from_email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Default from"
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="email_host",
            field=models.CharField(
                help_text="Can only contain a domain name, without the https://",
                max_length=100,
                verbose_name="Host domain",
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="email_port",
            field=models.PositiveSmallIntegerField(default=25, verbose_name="Port"),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="email_ssl_certfile",
            field=models.CharField(
                blank=True,
                help_text="Optional, can be used if either EMAIL_USE_SSL or EMAIL_USE_TLS is true.",
                max_length=500,
                verbose_name="SSL certfile",
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="email_ssl_keyfile",
            field=models.CharField(
                blank=True,
                help_text="Optional, can be used if either EMAIL_USE_SSL or EMAIL_USE_TLS is true.",
                max_length=500,
                verbose_name="SSL keyfile",
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUEST", "Instance creation requested"),
                    ("SCALINGO_APP_CREATED", "Scalingo app created"),
                    ("SCALINGO_DB_PROVISIONED", "Scalingo database provisioned"),
                    ("SCALINGO_ENV_VARS_SET", "Environment variables set in Scalingo"),
                    ("SF_CODE_DEPLOYED", "Sites Faciles code deployed"),
                    ("SF_INITIAL_DATA_DEPLOYED", "Sites Faciles initial data deployed"),
                ],
                default="REQUEST",
                max_length=42,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="wagtail_password_reset_enabled",
            field=models.BooleanField(
                default=True, verbose_name="Allow users to reset their password"
            ),
        ),
    ]
