# Generated by Django 5.1.5 on 2025-01-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instances", "0004_instance_alwaysdata_subdomain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailconfig",
            name="email_use_ssl",
            field=models.BooleanField(blank=True, null=True, verbose_name="Use SSL"),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="email_use_tls",
            field=models.BooleanField(blank=True, null=True, verbose_name="Use TLS"),
        ),
    ]
