# Generated by Django 5.1.5 on 2025-01-28 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instances", "0005_alter_emailconfig_email_use_ssl_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailconfig",
            options={
                "ordering": ["default_from_email"],
                "verbose_name": "email config",
            },
        ),
        migrations.CreateModel(
            name="ScalingoOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "scalingo_id",
                    models.SlugField(unique=True, verbose_name="scalingo_id"),
                ),
                ("finished_at", models.DateTimeField(verbose_name="updated at")),
                (
                    "status",
                    models.CharField(blank=True, max_length=42, verbose_name="status"),
                ),
                (
                    "operation_type",
                    models.CharField(blank=True, max_length=42, verbose_name="type"),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instances.instance",
                        verbose_name="instance",
                    ),
                ),
            ],
            options={
                "verbose_name": "operation",
                "ordering": ["-created_at"],
            },
        ),
    ]
