# Generated by Django 5.1.5 on 2025-01-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instances", "0006_alter_emailconfig_options_scalingooperation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scalingooperation",
            name="finished_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="updated at"
            ),
        ),
    ]
