# Generated by Django 5.1.5 on 2025-01-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instances", "0007_alter_scalingooperation_finished_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "bucket_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="bucket name"
                    ),
                ),
                (
                    "bucket_region",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="bucket region"
                    ),
                ),
                (
                    "host",
                    models.CharField(max_length=200, unique=True, verbose_name="host"),
                ),
                (
                    "storage_secrets_id",
                    models.PositiveSmallIntegerField(verbose_name="storage secrets ID"),
                ),
            ],
            options={
                "verbose_name": "storage config",
                "ordering": ["bucket_name"],
            },
        ),
        migrations.AlterField(
            model_name="instance",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUEST", "Instance creation requested"),
                    ("SCALINGO_APP_CREATED", "Scalingo app created"),
                    ("SCALINGO_DB_PROVISIONED", "Scalingo database provisioned"),
                    ("SCALINGO_ENV_VARS_SET", "Environment variables set in Scalingo"),
                    ("SF_CODE_DEPLOYED", "Sites Faciles code deployed"),
                    ("SF_INITIAL_DATA_DEPLOYED", "Sites Faciles initial data deployed"),
                    ("SF_SUPERUSERS_CREATED", "Superusers created"),
                    ("FINISHED", "Deployment complete"),
                ],
                default="REQUEST",
                max_length=42,
                verbose_name="status",
            ),
        ),
        migrations.DeleteModel(
            name="ScalingoOperation",
        ),
    ]
