# Generated by Django 5.1.5 on 2025-01-29 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instances", "0008_storageconfig_alter_instance_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="storage_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="instances.storageconfig",
                verbose_name="Storage configuration",
            ),
        ),
    ]
