# Generated by Django 5.2 on 2025-04-14 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instances", "0009_instance_storage_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScalingoAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="User name"
                    ),
                ),
                (
                    "secrets_id",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="Scalingo secrets ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Scalingo account",
                "ordering": ["username"],
            },
        ),
        migrations.AddField(
            model_name="instance",
            name="scalingo_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="instances.scalingoaccount",
                verbose_name="Owner in Scalingo",
            ),
        ),
    ]
