# Generated by Django 5.2 on 2025-06-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instances", "0009_instance_storage_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="git_branch",
            field=models.CharField(
                default="production",
                help_text="Choose the version of Sites Faciles to deploy. Please leave the default value if you are not a dev.",
                max_length=100,
                verbose_name="Git branch",
            ),
        ),
    ]
