# Generated by Django 5.2 on 2025-06-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instances", "0010_instance_git_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="auto_upgrade",
            field=models.BooleanField(
                default=True, verbose_name="Automatically deploy new releases"
            ),
        ),
    ]
