# Generated by Django 5.2 on 2025-06-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instances", "0011_instance_auto_upgrade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUEST", "Instance creation requested"),
                    ("SCALINGO_APP_CREATED", "Scalingo app created"),
                    ("SCALINGO_DB_PROVISIONED", "Scalingo database provisioned"),
                    ("SCALINGO_ENV_VARS_SET", "Environment variables set in Scalingo"),
                    ("SF_CODE_DEPLOYED", "Sites Faciles code deployed"),
                    ("SF_SUPERUSERS_CREATED", "Superusers created"),
                    ("FINISHED", "Initial deployment complete"),
                ],
                default="REQUEST",
                max_length=42,
                verbose_name="status",
            ),
        ),
    ]
