# Generated by Django 5.2.3 on 2025-07-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instances", "0012_alter_instance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="auto_upgrade",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck this box for headless instances.",
                verbose_name="Automatically deploy new releases",
            ),
        ),
    ]
