# Generated by Django 5.2.7 on 2025-11-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instances", "0013_alter_instance_auto_upgrade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instance",
            name="storage_config",
        ),
        migrations.AddField(
            model_name="instance",
            name="s3_bucket_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="S3 bucket name"
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="s3_bucket_region",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="S3 bucket region"
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="s3_host",
            field=models.CharField(blank=True, max_length=255, verbose_name="S3 host"),
        ),
        migrations.AddField(
            model_name="instance",
            name="s3_key_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="S3 key ID"
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="s3_key_secret",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="S3 key secret"
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="s3_location",
            field=models.CharField(
                blank=True,
                default="medias/",
                max_length=255,
                verbose_name="S3 location",
            ),
        ),
        migrations.DeleteModel(
            name="StorageConfig",
        ),
    ]
