name: Django CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: db_user
          POSTGRES_PASSWORD: db_password
          POSTGRES_DB: db_name
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Install just
        uses: extractions/setup-just@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          uv sync --no-group dev
      - name: Copy empty .env.example to .env
        run: |
          cp .env.example .env
      - name: Run the unit tests
        run: |
          just test
